USE [mgf_demo];
GO
ALTER DATABASE [mgf_demo] SET COMPATIBILITY_LEVEL = 150;
GO
ALTER DATABASE SCOPED CONFIGURATION CLEAR PROCEDURE_CACHE;
GO
ALTER DATABASE mgf_demo SET QUERY_STORE CLEAR ALL;
GO

